# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='car name')),
                ('index_char', models.CharField(blank=True, max_length=10, verbose_name='for quick location')),
            ],
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_year', models.IntegerField(default=0, verbose_name='model create year')),
                ('front', models.CharField(blank=True, max_length=100, verbose_name='front feature')),
                ('front_photo', models.CharField(blank=True, max_length=100, verbose_name='front photo')),
                ('back', models.CharField(blank=True, max_length=100, verbose_name='back feature')),
                ('back_photo', models.CharField(blank=True, max_length=100, verbose_name='back photo')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='car model name')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='backend.CarBrand')),
            ],
        ),
        migrations.CreateModel(
            name='MarkFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='特征名')),
            ],
        ),
        migrations.CreateModel(
            name='MarkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(default='', max_length=500, verbose_name='文件路径')),
            ],
        ),
        migrations.CreateModel(
            name='MarkObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='对象名')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='backend.MarkFile')),
            ],
        ),
        migrations.CreateModel(
            name='MarkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='任务名')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'default_related_name': 'files',
            },
        ),
        migrations.CreateModel(
            name='MarkUserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MarkTask')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='markfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backend.MarkTask'),
        ),
        migrations.AddField(
            model_name='markfeature',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featurs', to='backend.MarkObject'),
        ),
        migrations.AddField(
            model_name='carfeature',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CarModel'),
        ),
    ]
