# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marktask',
            name='user_created',
            field=models.DateTimeField(default=None, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='markfeature',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='backend.MarkObject'),
        ),
    ]
