# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0002_auto_20171116_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='object_id',
            field=models.IntegerField(default=0),
        ),
    ]
