# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171122_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='object_id',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.CarBrand'),
        ),
    ]
