# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171122_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='特征名')),
            ],
        ),
        migrations.CreateModel(
            name='MarkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(default='', max_length=500, verbose_name='文件路径')),
            ],
        ),
        migrations.CreateModel(
            name='MarkObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='对象名')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='backend.MarkFile')),
            ],
        ),
        migrations.CreateModel(
            name='MarkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='任务名')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='backend.CarBrand'),
        ),
        migrations.AddField(
            model_name='markfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backend.MarkTask'),
        ),
        migrations.AddField(
            model_name='markfeature',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featurs', to='backend.MarkObject'),
        ),
    ]
