# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171122_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='object_id',
        ),
    ]
