# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171122_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MarkTask'),
        ),
    ]
