# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171122_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marktask',
            options={'permissions': (('can_create_mark_task', '创建标注任务权限'),)},
        ),
        migrations.AlterField(
            model_name='markfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MarkTask'),
        ),
    ]
