# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171214_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marktask',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
