# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171122_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marktask',
            options={'permissions': (('can_create_mark_task', 'add mark task privilege'),)},
        ),
    ]
