# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20171122_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marktask',
            options={},
        ),
        migrations.AlterField(
            model_name='markfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backend.MarkTask'),
        ),
    ]
